<?php
/**
 * Cash Management System - Setup Wizard
 * Helps users configure database connection without editing code.
 */

session_start();

// If configuration already exists, redirect to home
if (file_exists('config/db_credentials.php')) {
    header('Location: index.php');
    exit;
}

$message = '';
$status = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $host = trim($_POST['db_host']);
    $user = trim($_POST['db_user']);
    $pass = trim($_POST['db_pass']);
    $name = trim($_POST['db_name']);
    
    // 1. Test Connection
    try {
        $dsn = "mysql:host=$host;dbname=$name;charset=utf8mb4";
        $options = [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION];
        $pdo = new PDO($dsn, $user, $pass, $options);
        
        // 2. Write to config file
        $config_content = "<?php\n\n";
        $config_content .= "// Auto-generated by Setup Wizard\n";
        $config_content .= "define('DB_HOST', '" . addslashes($host) . "');\n";
        $config_content .= "define('DB_NAME', '" . addslashes($name) . "');\n";
        $config_content .= "define('DB_USER', '" . addslashes($user) . "');\n";
        $config_content .= "define('DB_PASS', '" . addslashes($pass) . "');\n";
        $config_content .= "define('DB_CHARSET', 'utf8mb4');\n";
        
        if (file_put_contents('config/db_credentials.php', $config_content)) {
            
            // 3. Auto-Import Database Schema
            try {
                $sqlFile = 'database.sql';
                if (file_exists($sqlFile)) {
                    $sql = file_get_contents($sqlFile);
                    
                    // Remove comments and split by semicolon
                    $lines = explode(";", $sql);
                    $imported = 0;
                    
                    foreach ($lines as $line) {
                        $line = trim($line);
                        // Skip empty lines and comments
                        if (!empty($line) && strpos($line, '--') !== 0 && strpos($line, '/*') !== 0) {
                            try {
                                $pdo->exec($line);
                                $imported++;
                            } catch (PDOException $e) {
                                // Ignore duplicate table errors or minor issues
                                error_log("SQL Error: " . $e->getMessage());
                            }
                        }
                    }
                    $status = 'success';
                    $message = "Configuration saved & Database imported ($imported queries executed)! <br>Redirecting to homepage...";
                } else {
                    $status = 'warning';
                    $message = "Configuration saved, but 'database.sql' not found. You may need to import it manually.";
                }
            } catch (Exception $e) {
                $status = 'warning';
                $message = "Configuration saved, but automatic database import failed: " . $e->getMessage();
            }

            // Redirect after 3 seconds
            header("refresh:3;url=index.php");
        } else {
            $status = 'error';
            $message = "Connection successful, but failed to write 'config/db_credentials.php'. <br>Please check folder permissions or create the file manually.";
        }
    } catch (PDOException $e) {
        $status = 'error';
        $message = "Connection Failed: " . $e->getMessage();
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Setup - Cash Management System</title>
    <link rel="stylesheet" href="assets/css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
            color: white;
            font-family: 'Inter', sans-serif;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .setup-card {
            background: rgba(30, 41, 59, 0.8);
            backdrop-filter: blur(10px);
            padding: 2.5rem;
            border-radius: 1rem;
            border: 1px solid rgba(255,255,255,0.1);
            width: 100%;
            max-width: 500px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.3);
        }
        .form-group {
            margin-bottom: 1.5rem;
        }
        label {
            display: block;
            margin-bottom: 0.5rem;
            color: #94a3b8;
        }
        input {
            width: 100%;
            padding: 0.75rem;
            border-radius: 0.5rem;
            background: rgba(15, 23, 42, 0.6);
            border: 1px solid rgba(255,255,255,0.1);
            color: white;
            font-size: 1rem;
        }
        input:focus {
            outline: none;
            border-color: #6366f1;
            box-shadow: 0 0 0 2px rgba(99, 102, 241, 0.2);
        }
        button {
            width: 100%;
            padding: 0.875rem;
            background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%);
            color: white;
            border: none;
            border-radius: 0.5rem;
            font-weight: 600;
            cursor: pointer;
            transition: opacity 0.2s;
        }
        button:hover {
            opacity: 0.9;
        }
        .alert {
            padding: 1rem;
            border-radius: 0.5rem;
            margin-bottom: 1.5rem;
            font-size: 0.9rem;
        }
        .alert-error {
            background: rgba(239, 68, 68, 0.2);
            border: 1px solid rgba(239, 68, 68, 0.4);
            color: #fca5a5;
        }
        .alert-success {
            background: rgba(34, 197, 94, 0.2);
            border: 1px solid rgba(34, 197, 94, 0.4);
            color: #86efac;
        }
    </style>
</head>
<body>
    <div class="setup-card">
        <h2 style="margin-bottom: 0.5rem;">⚙️ System Setup</h2>
        <p style="color: #94a3b8; margin-bottom: 2rem;">Configure your database connection</p>
        
        <?php if ($message): ?>
            <div class="alert alert-<?php echo $status; ?>">
                <?php echo $message; ?>
            </div>
        <?php endif; ?>

        <?php if ($status !== 'success'): ?>
        <form method="POST">
            <div class="form-group">
                <label>Database Host</label>
                <input type="text" name="db_host" placeholder="e.g. sql123.infinityfree.com" value="<?php echo htmlspecialchars($_POST['db_host'] ?? 'localhost'); ?>" required>
            </div>
            
            <div class="form-group">
                <label>Database Name</label>
                <input type="text" name="db_name" placeholder="e.g. if0_35..._cash_system" value="<?php echo htmlspecialchars($_POST['db_name'] ?? ''); ?>" required>
            </div>
            
            <div class="form-group">
                <label>Database Username</label>
                <input type="text" name="db_user" placeholder="e.g. if0_35..." value="<?php echo htmlspecialchars($_POST['db_user'] ?? ''); ?>" required>
            </div>
            
            <div class="form-group">
                <label>Database Password</label>
                <input type="password" name="db_pass" placeholder="Hosting account password" required>
            </div>
            
            <button type="submit">Connect & Save Configuration</button>
        </form>
        <?php endif; ?>
    </div>
</body>
</html>
